package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class JobHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobHistoryAllPropertiesEquals(JobHistory expected, JobHistory actual) {
        assertJobHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertJobHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobHistoryAllUpdatablePropertiesEquals(JobHistory expected, JobHistory actual) {
        assertJobHistoryUpdatableFieldsEquals(expected, actual);
        assertJobHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobHistoryAutoGeneratedPropertiesEquals(JobHistory expected, JobHistory actual) {
        assertThat(actual)
            .as("Verify JobHistory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobHistoryUpdatableFieldsEquals(JobHistory expected, JobHistory actual) {
        assertThat(actual)
            .as("Verify JobHistory relevant properties")
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getLanguage()).as("check language").isEqualTo(expected.getLanguage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertJobHistoryUpdatableRelationshipsEquals(JobHistory expected, JobHistory actual) {
        assertThat(actual)
            .as("Verify JobHistory relationships")
            .satisfies(a -> assertThat(a.getJob()).as("check job").isEqualTo(expected.getJob()))
            .satisfies(a -> assertThat(a.getDepartment()).as("check department").isEqualTo(expected.getDepartment()))
            .satisfies(a -> assertThat(a.getEmployee()).as("check employee").isEqualTo(expected.getEmployee()));
    }
}
