on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: sudo apt install maven

      - run: npm i generator-jhipster -g

      - run: |
          echo "y" | rm -R app
          mkdir app

      - run: |
          cd app
          mkdir client
          cd client
          echo "a" | jhipster jdl ../../jdl/app.jdl --skip-git --skip-server

      - run: |
          cd app
          mkdir server
          cd server
          echo "a" | jhipster jdl ../../jdl/app.jdl --skip-git --skip-client

      - uses: peter-evans/create-pull-request@v3
