on:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: lts/*
          
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: sudo apt install maven

      - run: |
          echo Node version
          node -v
          echo NPM version
          npm -v
          git version

      - run: git clone --depth=1 https://github.com/jhipster/generator-jhipster.git

      - run: |
          pwd
          ls -a

      - run: |
          cd generator-jhipster
          npm un generator-jhipster
          sudo npm un generator-jhipster -g
          npm i
          sudo npm link

      - run: |
          echo "y" | rm -R app
          mkdir app

      - run: |
          cd app
          mkdir client
          cd client
          echo "a" | jhipster jdl ../../jdl/app.jdl --skip-git --skip-server

      - run: |
          cd app
          mkdir server
          cd server
          echo "a" | jhipster jdl ../../jdl/app.jdl --skip-git --skip-client

      - run: |
          pwd
          ls -a

      - run: |
          echo "y" | rm -R generator-jhipster
#         echo "y" | rm -R .gitmodules

      # - run: mv sonar-project.properties app/server

      - uses: peter-evans/create-pull-request@v3
